# Site settings
title: Digital Arquivos
email: contato@digitalarquivos.com.br
description: > Soluções em Arquivologia
baseurl: "" # the subpath of your site, e.g. /blog/
url: "digitalarquivos.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
